### PR TITLE
TRV support

### PR DESCRIPTION
**Pull request by MagicalTrev89**
Latest update for TRV support includes HVAC actions as well,

HVAC Modes supported:
- Heating
- Idle
- Off

### CODE REVIEW

**Comment by Rendili** [comment]
@MagicalTrev89 
I have merged this in on the TRV-Support branch and updated the library version to 0.2.19.dev1 with the intention of creating a dev version of the library of this branch

Please could you update to Rendili/home-assistant TRV-Support branch your changes needed for the component in HA side?

**Comment by MagicalTrev89** [comment]
Done! ✅

**Comment by Rendili** [comment]
I have updated my TRV-Support branch for home-assisant to the dev library 0.2.19.dev1 with your merges
If you have a dev home-assistant setup, you can clone and switch branches to this and fully test end to end with the library. I will do this too as soon as i have re-built my dev box (had to update due to old linux and python versions).
(or i guess rebase your branch from mine?)

**Comment by Rendili** [comment]
@MagicalTrev89 , a new version of the pyhiveapi library 0.2.19 has been created with your TRV changes and an update to support wired thermostats
Please could you create a PR for home assistant for the required HA file changes needed and use the library version 0.2.19?

**Comment by MagicalTrev89** [comment]
@Rendili Thanks, sorry for the delay, been having some problems with my Pi .. will raise the pr shortly ...

**Comment by Rendili** [comment]
@MagicalTrev89 no problem, great stuff thanks

**Comment by MagicalTrev89** [comment]
@Rendili i have done a PR to change the version of pyhiveapi against your fork of HA... hope this is what you meant?, i have updated my HA and initial test appears to be working as expected.

**Pull request merged**
